feat: Multimodal block display + Steamship agent
a16z-infra/companion-app pull request #49
Opened 2023-07-12 13:40 UTC by eob

This PR adds two separate (but related) features:

1. Basic support in the UI for multimodal blocks (think Notion-style) as the agent response type. String completions, as provided before, are rendered as a text block.
2. A Steamship companion of Rick (from Rick & Morty), which supports audio and image responses in addition to text.

Note: We've wire this agent to a hosted copy of Rick w/ custom voice & character knowledge, for which you'll need an API key to access -- we can DM that key for your use.

![image](https://github.com/a16z-infra/companion-app/assets/63262/6f480e90-ac7e-4c71-be3f-b9211f422261)

2023-07-12 23:00 UTC, ykhli commented
Thanks so much for this @eob! I tried it out on codespaces but for some reason the audio / image generation didn't work. I can check out the branch locally to see why thats the case. 

Would be super helpful if you could add more instructions to creating a user's own agent on steamship / have a ready-to-use agent people can deploy easily when they first launch this app too!

2023-07-14 12:17 UTC, EniasCailliau commented
@ykhli I've added a PR that adds more instructions for creating a user's own agent on Steamship. Users will be able to either use the pre-deployed instance featured in this PR or can instantiate their own companions with the instructions in the readme. 

Here's the PR #57

2023-07-14 12:50 UTC, EniasCailliau commented
@ykhli audio/image generation is now fixed. Sorry for the confusion! 

![image](https://github.com/a16z-infra/companion-app/assets/13366849/627b1163-8785-4dfd-b3ac-1e3b697937aa)

2023-07-22 23:46 UTC, jenniferli23 commented on README.md
> +Next, [build an agent](https://www.steamship.com/learn/agent-guidebook), create your own instance of it, and connect it in `companions.json` using the *Rick* example as a guide.
```suggestion
g. **Steamship API key**

You can connect a Steamship agent instance as an LLM with personality, voice and image generation capabilities built in. It also includes its own vector storage and tools. To do so:

- Create an account on [Steamship](https://steamship.com/account)
- Copy the API key from your account settings page
- Add it as the `STEAMSHIP_API_KEY` variable 

If you'd like to create your own character personality, add a custom voice, or use a different image model, visit [Steamship Agent Guidebook](https://www.steamship.com/learn/agent-guidebook), create your own instance and connect it in `companions.json` using the *Rick* example as a guide.
```

2023-07-23 00:00 UTC, jenniferli23 commented on companions/companions.json
> +    "telegram": "OPTIONAL_TELEGRAM_LINK"
```suggestion
 
```

2023-07-23 00:01 UTC, jenniferli23 commented on companions/companions.json
> +    "telegram": "OPTIONAL_TELEGRAM_LINK"
Please remove the rest of the telegram option except for Rick

2023-07-23 00:06 UTC, jenniferli23 commented on companions/companions.json
> +    "title": "I can generate voice and pictures.",
```suggestion
    "title": "I can generate voice and pictures. You also can talk to me on Telegram",
```

2023-07-23 00:06 UTC, jenniferli23 requested changes
Looks great! Just a few suggestions for easy following.

2023-07-24 17:10 UTC, eob commented
Thanks for the feedback! Merged in your suggestions and pulled the `telegram` link on all of them for now. We can send another PR that adds it back in, conditionally on the field being present, later if there's interest.

2023-07-26 13:00 UTC, eob commented
@jenniferli23 one last update -- Enias did some prompt engineering to get the image quality much better, and added in the telegram link for just the Rick bot.

I think this is ready to merge, but lmk if you need anymore changes!

<img width="746" alt="image" src="https://github.com/a16z-infra/companion-app/assets/63262/8f0f339a-1825-4a51-88fb-4555cdb0db10">

2023-08-14 08:05 UTC, merged